# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - npm install;exit 0
job2:
  stage: test
  script:
    - npm test
job3:
  stage: deploy
  script:
    - cd /opt/revive-bot/apps/revivebot
    - git pull
    - pod stop revivebot
    - pod start revivebot
  only:
    - master
  