# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
variables:
  settings_file: |
    {
      "owners": [
          "184547913509109761",
          "61189081970774016",
          "272840951414915072",
          "184656803978543104",
          "189917679119892480",
          "184815005303046144",
          "162657378083274753",
          "183943736839897099",
          "114811335195230209"
      ],
      "disabled-channels": [
          "323175153779474432"
      ],
      "identifier": "~",
      "delimiter": " ",
      "slowmov": [],
      "game-roles": {
          "bf2": "351447229355261955",
          "bf2142": "351727965916364801",
          "bfheroes": "351728164952604682"
      },
      "token": "$DISCORD_TOKEN",
      "influx_host" : "$INFLUX_HOST",
      "revive-api" : "$revive-api"
    }
stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - npm install;exit 0
    - echo $SECRET_IS_WORKING
job2:
  stage: test
  script:
    - echo "$settings_file" > settings.json
    - npm test
job3:
  stage: deploy
  script:
    - whoami
    - cd /opt/revive-bot/apps/revivebot
    - sudo git pull
    - echo "$settings_file" > settings.json
    - npm install
    - sudo DISCORD_TOKEN=$DISCORD_TOKEN pm2 restart index.js --update-env --name revivebot
  only:
    - master
  