# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - npm install;exit 0
    - echo $SECRET_IS_WORKING
job2:
  stage: test
  script:
    - npm test
job3:
  stage: deploy
  script:
    - whoami
    - cd /opt/revive-bot/apps/
    - sudo git pull
    - npm install
    - sudo DISCORD_TOKEN=$DISCORD_TOKEN pm2 restart index.js --update-env --name revivebot
  only:
    - master
  